package io.kestra.plugin.meta.facebook.enums;

public enum PostMetric {
    POST_REACTIONS_LIKE_TOTAL,
    POST_REACTIONS_LOVE_TOTAL,
    POST_REACTIONS_WOW_TOTAL,
    POST_REACTIONS_HAHA_TOTAL,
    POST_REACTIONS_SORRY_TOTAL,
    POST_REACTIONS_ANGER_TOTAL,
    POST_IMPRESSIONS,
    POST_ENGAGED_USERS,
    POST_CLICKS,
    POST_REACTIONS_BY_TYPE_TOTAL
}
